version: '3.1'

services:
  api:
    build: .
    container_name: api
    ports: 
      - "8888:8888"

  db:
    container_name: db
    ports:
      - "6101:6101"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:14.3-alpine
    command:
      - "postgres"
      - "-c"
      - "port=6101"
    volumes:
      - db_vol:/var/lib/postgresql/data/
    networks:
      - internal_net

volumes:
  db_vol: {}


networks:
  internal_net:
    driver: bridge