name: api_app_flutter
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  freezed: ^2.3.2
  flutter_bloc: ^8.1.1
  dio: ^5.0.0
  get_it: ^7.2.0
  freezed_annotation: any
  json_annotation: any
  json_serializable: any
  build_runner: any
  shared_preferences: ^2.0.15 
  requests: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
