name: project_lesson
description: An empty conduit application.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  conduit: ^4.1.6
  test: ^1.16.5
  jaguar_jwt: ^3.0.0